### PR TITLE
Use MD5 explicitly in jmv_autodep

### PR DESCRIPTION
**Pull request by cvcal**

### CODE REVIEW

**Comment by cvcal** [comment]
The failures seem unrelated, the build is broken, AFAIKT

**Comment by cvcal** [comment]
@philwo

**Comment by philwo** [comment]
Yeah, looks broken to me. Possibly because of the upgraded JDK in Bazel being incompatible with this.

I'm just going to merge your change.

**Comment by lucapette** [comment]
```
ERROR: /Users/lucapette/src/tools_jvm_autodeps/java/com/google/devtools/javatools/jade/pkgloader/BUILD:5:1: Building java/com/google/devtools/javatools/jade/pkgloader/GrpcLocalServer.jar (1 source file) and running annotation processors (OptionProcessor) failed (Exit 1)
java/com/google/devtools/javatools/jade/pkgloader/GrpcLocalServer.java:19: error: cannot find symbol
import com.google.devtools.build.lib.vfs.DigestHashFunction;
                                        ^
  symbol:   class DigestHashFunction
  location: package com.google.devtools.build.lib.vfs
Target //java/com/google/devtools/javatools/jade/pkgloader:GrpcLocalServer_deploy.jar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.657s, Critical Path: 0.36s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

As far as I can say this commit broke the build (I can successfully build the server at  c00ebee)

**Comment by philwo** [comment]
@cvcal Do you have a quick fix for this? We can also revert this PR alternatively.

**Comment by philwo** [comment]
I had a look at this.

The problem is that DigestHashFunction didn't exist in Bazel 0.15.2, so we have to update the referenced version of Bazel in the WORKSPACE file to at least 0.16.0.

I fixed this in https://github.com/bazelbuild/tools_jvm_autodeps/commit/a467206303a9979754c971430c8f08fb24cb8281.

**Comment by cvcal** [comment]
Thanks!

**Pull request merged**
